sensor:
  - name: "Family Status"
    state_topic: "house/family/status"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "Family Arrived"
    state_topic: "house/family/arrived"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "Jeff Last Known Location"
    state_topic: "house/jeff/last_known_location"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "Kat Last Known Location"
    state_topic: "house/kat/last_known_location"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "daily_agenda_raw"
    state_topic: "house/daily/events"
  - name: "Jeff Destination"
    state_topic: "jeff/driving/destination"
  - name: "Kat Destination"
    state_topic: "kat/driving/destination"